#!/bin/bash

# restore the kernel.pid_max to the default value and then delete the temp file created
sysctl -w kernel.pid_max=$(cat /home/deck/Android_Waydroid/orig_kernel.pid_max)
rm -f /home/deck/Android_Waydroid/orig_kernel.pid_max

# reset cage
cage -- bash -c 'wlr-randr'

# stop the waydroid container
sleep 10
systemctl stop waydroid-container.service
systemctl stop firewalld.service

# unmount the custom var directory for waydroid
umount /var/lib/waydroid
losetup -d $(losetup | grep waydroid.img | cut -d " " -f1)

# remove the offending packages
#steamos-readonly disable
#pacman -R cage wlroots0.18 --noconfirm
#pacman -U /home/deck/Android_Waydroid/pacman/libdisplay-info-0.3.0-1-x86_64.pkg.tar.zst --noconfirm

# enable the readonly
steamos-readonly enable
